[package]
name = "colorgen"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "4.0.1"
lazy_static = "1.4.0"
raytracer = { path = "../raytracer" }
regex = "1.7.1"
reqwest = "0.11.13"
scraper = "0.14.0"
tokio = { version = "1.9.0", features = ["full"] }
